# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PureTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PureTest
 pod 'Swinject'
 pod 'Pure'
  target 'PureTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PureTestUITests' do
    # Pods for testing
  end

end
